# Generated by Django 3.2.25 on 2024-05-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_auto_20240516_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retainerinvoice',
            name='customer_name1',
        ),
    ]
